### ISSUE TITLE
Ability to store payloads, so when we trigger, we can send the array of input payloads.

### ISSUE THREAD

**Issue by biddster** [biddster/node-red-contrib-topic-timeframe-trigger#1]
Like ReactiveCocoa's Zip Signal.

**Comment by 466** [comment]
Even though it's been a while and nothing seems to have changed within the repo,
I would love to have this feature too :)

Are you, by chance, going to implement something like this?

**Comment by biddster** [comment]
I can do, time has been my issue lately. I'll try to do it ASAP.

**Comment by biddster** [comment]
Fixed in 0.2.0. All of the messages received that caused the node to trigger are emitted in the outgoing message under the triggers property.
